export const CALENDAR_CHART_ROUTE = '/calendar_chart'
export const WORKS_ROUTE = '/works'
export const DOCUMENTS_ROUTE = '/documents'
export const PROGRESS_WORK = '/progress'
export const COMPUTERS_ROUTE = '/computers'
export const COMPONENTS_ROUTE = '/components'
